.TH "extension\ezsharenetwork\autoloads\eZShareNetworkTemplateOperators" 3 "Mon Mar 12 2012" "Version 1.0.0-RC" "eZ ShareNetwork" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extension\ezsharenetwork\autoloads\eZShareNetworkTemplateOperators \- 
.PP
Class operator to manage functions in template\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBoperatorList\fP ()"
.br
.RI "\fIReturn an array with the template operator name\&. \fP"
.ti -1c
.RI "\fBnamedParameterPerOperator\fP ()"
.br
.RI "\fIReturn true to tell the template engine that the parameter list exists per operator type\&. \fP"
.ti -1c
.RI "\fBnamedParameterList\fP ()"
.br
.RI "\fIReturns an array of named parameters, this allows for easier retrieval of operator parameters\&. \fP"
.ti -1c
.RI "\fBmodify\fP ($tpl, $operatorName, $operatorParameters, $rootNamespace, $currentNamespace, &$operatorValue, array $namedParameters, $placement)"
.br
.RI "\fIExecutes the PHP function for the operator cleanup and modifies \fI$operatorValue\fP\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBoperators\fP ()"
.br
.RI "\fIReturn the operators names\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$Operators\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class operator to manage functions in template\&. 

Class operator to manage functions in template
.PP
\fBAuthor:\fP
.RS 4
Adrien Loyant adrien.loyant@te-laval.fr
.RE
.PP
\fBDate:\fP
.RS 4
2012-01-01 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Public License v\&.2
.RE
.PP
extension 
.PP
Definition at line 17 of file ezsharenetworktemplateoperators\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBextension\\ezsharenetwork\\autoloads\\eZShareNetworkTemplateOperators::__construct\fP ()"

.PP
Constructor\&. The constructor for the operator
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 43 of file ezsharenetworktemplateoperators\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBextension\\ezsharenetwork\\autoloads\\eZShareNetworkTemplateOperators::modify\fP ($tpl, $operatorName, $operatorParameters, $rootNamespace, $currentNamespace, &$operatorValue, array $namedParameters, $placement)"

.PP
Executes the PHP function for the operator cleanup and modifies \fI$operatorValue\fP\&. Executes the PHP function for the operator cleanup and modifies \fI$operatorValue\fP 
.PP
\fBParameters:\fP
.RS 4
\fI$tpl\fP 
.br
\fI$operatorName\fP 
.br
\fI$operatorParameters\fP 
.br
\fI$rootNamespace\fP 
.br
\fI$currentNamespace\fP 
.br
\fI$operatorValue\fP This args is passed by reference 
.br
\fI$namedParameters\fP 
.br
\fI$placement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 95 of file ezsharenetworktemplateoperators\&.php\&.
.SS "\fBextension\\ezsharenetwork\\autoloads\\eZShareNetworkTemplateOperators::namedParameterList\fP ()"

.PP
Returns an array of named parameters, this allows for easier retrieval of operator parameters\&. Returns an array of named parameters, this allows for easier retrieval of operator parameters\&. 
.PP
\fBSee also:\fP
.RS 4
::namedParameterList
.RE
.PP
\fBReturns:\fP
.RS 4
multitype:multitype:multitype:string boolean number multitype:string boolean 
.RE
.PP

.PP
Definition at line 75 of file ezsharenetworktemplateoperators\&.php\&.
.SS "\fBextension\\ezsharenetwork\\autoloads\\eZShareNetworkTemplateOperators::namedParameterPerOperator\fP ()"

.PP
Return true to tell the template engine that the parameter list exists per operator type\&. Return true to tell the template engine that the parameter list exists per operator type, this is needed for operator classes that have multiple operators\&.
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 64 of file ezsharenetworktemplateoperators\&.php\&.
.SS "\fBextension\\ezsharenetwork\\autoloads\\eZShareNetworkTemplateOperators::operatorList\fP ()"

.PP
Return an array with the template operator name\&. Return an array with the template operator name\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 53 of file ezsharenetworktemplateoperators\&.php\&.
.SS "static \fBextension\\ezsharenetwork\\autoloads\\eZShareNetworkTemplateOperators::operators\fP ()\fC [static]\fP"

.PP
Return the operators names\&. Return the operators names
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 33 of file ezsharenetworktemplateoperators\&.php\&.
.SH "Field Documentation"
.PP 
.SS "\fBextension\\ezsharenetwork\\autoloads\\eZShareNetworkTemplateOperators::$Operators\fP\fC [protected]\fP"

.PP
Definition at line 25 of file ezsharenetworktemplateoperators\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for eZ ShareNetwork from the source code\&.
