.TH "D:/aloyant/workspace/ezsharenetwork/autoloads/ezsharenetworktemplateoperators.php" 3 "Mon Mar 12 2012" "Version 1.0.0-RC" "eZ ShareNetwork" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/aloyant/workspace/ezsharenetwork/autoloads/ezsharenetworktemplateoperators.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBextension\\ezsharenetwork\\autoloads\\eZShareNetworkTemplateOperators\fP"
.br
.RI "\fIClass operator to manage functions in template\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBextension\\ezsharenetwork\\autoloads\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for eZ ShareNetwork from the source code\&.
