.TH "D:/aloyant/workspace/ezsharenetwork/autoloads/eztemplateautoload.php" 3 "Mon Mar 12 2012" "Version 1.0.0-RC" "eZ ShareNetwork" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/aloyant/workspace/ezsharenetwork/autoloads/eztemplateautoload.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$eZTemplateOperatorArray\fP = array()"
.br
.ti -1c
.RI "\fB$eZTemplateOperatorArray\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$eZTemplateOperatorArray = array()"

.PP
Definition at line 5 of file eztemplateautoload\&.php\&.
.SS "$eZTemplateOperatorArray[]"
\fBInitial value:\fP
.PP
.nf
 array( 'script' => 'extension/ezsharenetwork/autoloads/ezsharenetworktemplateoperators\&.php',
                                    'class' => 'extension\ezsharenetwork\autoloads\eZShareNetworkTemplateOperators',
                                    'operator_names' => eZShareNetworkTemplateOperators::operators()
)
.fi
.PP
Definition at line 6 of file eztemplateautoload\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for eZ ShareNetwork from the source code\&.
